### ISSUE TITLE
Check Bower integration

### ISSUE THREAD

**Issue by IvanSanchez** [MazeMap/Leaflet.VisualClick#2]
- [x] Tag a release here
- [x] Make a local build
- [x] Upload a zipfile including `dist` to the release
- [x] `bower publish`
- [x] Do a `bower install Leaflet.VisualClick` somewhere else and see if the `dist` files work as expected

**Comment by dagjomar** [comment]
Is it some new pattern to include a zip-file in the dist? Haven't seen that much before. Pros?

**Comment by IvanSanchez** [comment]
The theory is that Bower will pull the stuff into the zipfile (with the built -i.e. autoprefixed- files), instead of the contents of the repo (unbuilt) at the tagged release.

**Comment by dagjomar** [comment]
In what step will that take place?
Isn't it equally easy to have the dist-folder in the repo? At least that way you can download the files and run the demo without having to npm install everything first?

**Comment by IvanSanchez** [comment]
Keeping built files in a repo is an anti-pattern :-)

That discussion happens every time with Leaflet.MarkerCluster, which keeps an explicitly out-of-sync copy of the built files in the repo, and causes pain in the long term.

**Comment by dagjomar** [comment]
Yeah I've heard... although on a general basis, I still find it convenient to get access to the built files. But I guess, the "right" solution is to have a seperate distribution/download page.

But I'm guessing the zip-file won't be added  to the repo either. Or?
So then...what's the differene between building the dist files, and building the zip-file with the dist-files?

Playing stupid here^^

**Comment by IvanSanchez** [comment]
> what's the difference between building the dist files, and building the zip-file with the dist-files?

The build system builds the `dist/*` files, then creates a `.zip` out of them ;-)
