### ISSUE TITLE
Marker.remove is not a function Error. 

### ISSUE THREAD

**Issue by rpark37** [MazeMap/Leaflet.VisualClick#5]
Hello, just wondering if there was a way to prevent or turnoff the error caused by the "marker.remove" function call?

'Uncaught TypeError: marker.remove is not a function'

(anonymous function) @ L.VisualClick.js:37
setTimeout (async)
L.Map.VisualClick.L.Handler.extend._onClick @ L.VisualClick.js:35
o.Mixin.Events.fireEvent @ leaflet-src.js:473
o.Map.o.Class.extend._fireMouseEvent @ leaflet-src.js:2194
o.Map.o.Class.extend._onMouseClick @ leaflet-src.js:2174
t.(anonymous function).s @ leaflet-src.js:6380

thanks,

**Comment by IvanSanchez** [comment]
> wondering if there was a way to...

[Yes](http://homepage.ntlworld.com./jonathan.deboynepollard/FGA/questions-with-yes-or-no-answers.html).

**Comment by dagjomar** [comment]
@rpark37 When are you getting this error? 
And yeah, it's possible to do a better check for it, so probably a quick fix

**Comment by dagjomar** [comment]
Thanks :+1:
