### ISSUE TITLE
Error adding to Webjars using bower

### ISSUE THREAD

**Issue by gavioto** [MazeMap/Leaflet.VisualClick#6]
http://www.webjars.org/bower -> add a new bower webjar

Failed!
No valid licenses found. Detected licenses: Apache
The acceptable licenses on BinTray are at: https://bintray.com/docs/api/#_footnote_1
License detection first uses the package metadata (e.g. package.json or bower.json) and falls back to looking for a LICENSE, LICENSE.txt, or LICENSE.md file in the master branch of the GitHub repo.
Since these methods failed to detect a valid license you will need to work with the upstream project to add discoverable license metadata to a release or to the GitHub repo.

If you feel you have reached this failure in error, please file an issue: https://github.com/webjars/webjars/issues

Created Bower WebJar
Fetched Bower zip
Generated POM
Converted dependencies to Maven
Got Bower info
Determined Artifact Name: Leaflet.VisualClick
Starting Deploy

**Comment by IvanSanchez** [comment]
Closed by #7.

@gavioto In the future, please explain yourself better in bug reports - a copy-paste of an error message is _not_ a bug report. I suggest you read http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
