### ISSUE TITLE
How to listen Mouse wheel?

### ISSUE THREAD

**Issue by UinJack** [MazeMap/Leaflet.VisualClick#9]
Hi I find no Mouse wheel listener in API ,if I need animate when roll mouse wheel ,how to realize.

thanks

**Comment by IvanSanchez** [comment]
Add `"mousewheel"` and/or `"wheel"` to the `visualClickEvents` option. This is a space-separated string of DOM events. See https://github.com/MazeMap/Leaflet.VisualClick/blob/master/src/L.VisualClick.js#L66
